In [1]:
import pandas as pd
from pandas import DataFrame
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder

In [2]:
FULL_DATASET_NAME = 'data/landing_club/accepted_2007_to_2018Q4.csv'
SMALL_SAMPLE_DATASET_NAME = 'data/landing_club/accepted_2007_to_2018Q4_small_sample.csv'
SMALL_HEAD_DATASET_NAME = 'data/landing_club/accepted_2007_to_2018Q4_small_head.csv'
MEDIUM_SAMPLE_DATASET_NAME = 'data/landing_club/accepted_2007_to_2018Q4_medium_sample.csv'
MEDIUM_HEAD_DATASET_NAME = 'data/landing_club/accepted_2007_to_2018Q4_medium_head.csv'
USED_DATASET_NAME = MEDIUM_HEAD_DATASET_NAME

In [3]:
COL_NAMES = ['loan_amnt', 'home_ownership', 'annual_inc', 'int_rate']
FEATURE_NAMES = ['loan_amnt', 'home_ownership', 'annual_inc']
LABEL_NAME = 'int_rate'
record_count = 10000
# acc_raw_df = pd.read_csv(FULL_DATASET_NAME, usecols = COL_NAMES)
# acc_raw_df.sample(record_count).to_csv(SMALL_SAMPLE_DATASET_NAME, columns=col_names)
# acc_raw_df.head(record_count).to_csv(SMALL_HEAD_DATASET_NAME, columns=col_names)
# acc_raw_df.sample(record_count).to_csv(MEDIUM_SAMPLE_DATASET_NAME, columns=COL_NAMES)
# acc_raw_df.head(record_count).to_csv(MEDIUM_HEAD_DATASET_NAME, columns=COL_NAMES)

In [4]:
from landing_club_dataset import Landing_Club_Dataset
dataset = Landing_Club_Dataset(USED_DATASET_NAME, LABEL_NAME, COL_NAMES)
dataset.X_df

<class 'pandas.core.series.Series'>
AAAAAAAA
      loan_amnt  annual_inc  x0_MORTGAGE  x0_OWN  x0_RENT
0        3600.0     55000.0          1.0     0.0      0.0
1       24700.0     65000.0          1.0     0.0      0.0
2       20000.0     63000.0          1.0     0.0      0.0
3       35000.0    110000.0          1.0     0.0      0.0
4       10400.0    104433.0          1.0     0.0      0.0
...         ...         ...          ...     ...      ...
9995     5000.0     38000.0          0.0     0.0      1.0
9996    16000.0    100000.0          0.0     0.0      1.0
9997    24000.0     80000.0          1.0     0.0      0.0
9998    10000.0     45000.0          1.0     0.0      0.0
9999    21000.0     86000.0          1.0     0.0      0.0

[10000 rows x 5 columns]


/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


loan_amnt  annual_inc  x0_MORTGAGE  x0_OWN  x0_RENT
0        3600.0     55000.0          1.0     0.0      0.0
1       24700.0     65000.0          1.0     0.0      0.0
2       20000.0     63000.0          1.0     0.0      0.0
3       35000.0    110000.0          1.0     0.0      0.0
4       10400.0    104433.0          1.0     0.0      0.0
...         ...         ...          ...     ...      ...
9995     5000.0     38000.0          0.0     0.0      1.0
9996    16000.0    100000.0          0.0     0.0      1.0
9997    24000.0     80000.0          1.0     0.0      0.0
9998    10000.0     45000.0          1.0     0.0      0.0
9999    21000.0     86000.0          1.0     0.0      0.0

[10000 rows x 5 columns]

In [5]:

df = pd.read_csv(USED_DATASET_NAME, usecols=COL_NAMES)
print(len(df))

df['home_ownership'].value_counts()

10000


MORTGAGE    4925
RENT        3934
OWN         1141
Name: home_ownership, dtype: int64

In [6]:
# One Hot encode home_ownership columns
pd.get_dummies(df, columns=['home_ownership'])

loan_amnt  annual_inc  int_rate  home_ownership_MORTGAGE  \
0        3600.0     55000.0     13.99                        1   
1       24700.0     65000.0     11.99                        1   
2       20000.0     63000.0     10.78                        1   
3       35000.0    110000.0     14.85                        1   
4       10400.0    104433.0     22.45                        1   
...         ...         ...       ...                      ...   
9995     5000.0     38000.0     13.67                        0   
9996    16000.0    100000.0      9.76                        0   
9997    24000.0     80000.0     13.18                        1   
9998    10000.0     45000.0      9.17                        1   
9999    21000.0     86000.0     11.22                        1   

      home_ownership_OWN  home_ownership_RENT  
0                      0                    0  
1                      0                    0  
2                      0                    0  
3                      0                    0  
4                      0                    0  
...                  ...                  ...  
9995                   0                    1  
9996                   0                    1  
9997                   0                    0  
9998                   0                    0  
9999                   0                    0  

[10000 rows x 6 columns]

In [7]:
categories = df['home_ownership'].to_numpy().reshape(-1,1)
oh_encoder = OneHotEncoder(sparse=False)
transformed = oh_encoder.fit_transform(categories)
print(transformed)
oh_encoder.get_feature_names_out()
ohe_df = pd.DataFrame(transformed, columns=oh_encoder.get_feature_names_out())
df1 = df.join(ohe_df)
df1.drop(columns=['home_ownership'])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


loan_amnt  annual_inc  int_rate  x0_MORTGAGE  x0_OWN  x0_RENT
0        3600.0     55000.0     13.99          1.0     0.0      0.0
1       24700.0     65000.0     11.99          1.0     0.0      0.0
2       20000.0     63000.0     10.78          1.0     0.0      0.0
3       35000.0    110000.0     14.85          1.0     0.0      0.0
4       10400.0    104433.0     22.45          1.0     0.0      0.0
...         ...         ...       ...          ...     ...      ...
9995     5000.0     38000.0     13.67          0.0     0.0      1.0
9996    16000.0    100000.0      9.76          0.0     0.0      1.0
9997    24000.0     80000.0     13.18          1.0     0.0      0.0
9998    10000.0     45000.0      9.17          1.0     0.0      0.0
9999    21000.0     86000.0     11.22          1.0     0.0      0.0

[10000 rows x 6 columns]

In [8]:
a = [1, 2]
b = [[3,4,5]]
a + b[0]

[1, 2, 3, 4, 5]

In [9]:
from landing_club_prepost import LandingClubPrePost
import pickle as p

wrapper_file = open('landing_club_prepost.pickle', 'rb')
prepost: LandingClubPrePost = p.load(wrapper_file)

prepost.preprocess(35000.0, 'RENT', 110000.0)


[0. 0. 1.]
DUDEL1
[35000.0, 110000.0]
[35000.0, 110000.0, 0.0, 0.0, 1.0]
[[ 2.27035635  0.4585379  -0.9965061  -0.35781501  1.25525297]]


[2.2703563485866662,
 0.458537904565502,
 -0.996506103618562,
 -0.35781501489511314,
 1.2552529676835391]